### ISSUE TITLE
Texture not updating when file path changes

### ISSUE THREAD

**Issue by zauner** [bj-rn/VL.PDFReader#1]
Hi! Very cool, thank you for sharing this.

I might have stumbled upon a bug while playing around. It seems PDFReader (Stride) has trouble updating the output texture when `Preload Pages` is lower than the number of total pages.

In that case, `Output` does not change, and `Loaded Textures` kind of has a mixture of the current PDF and the previous one.

I can reproduce this in the "Explanation Overview PDF nodes" help patch, when trying to load any 1-page PDF inside the "Stride Texture" frame (while keeping Preload Pages at 1)

**Comment by bj-rn** [comment]
Thanks. Should be fixed in versions >= 1.0.1.
