### ISSUE TITLE
Can’t build VL.PDFReader nuget

### ISSUE THREAD

**Issue by juergenBW93** [bj-rn/VL.PDFReader#3]
I have a problem with the VL.PDFReader nuget. 
I get no build error at all when building my application with gamma 6.6 but when i try to start it it doesn't even open a window. I get the same problem on multiple computers. 

The Event Viewer says the following:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Stride.Graphics, Version=4.2.0.2149, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Stride.Graphics, Version=4.2.0.2149, Culture=neutral, PublicKeyToken=null'
   at Stride.Core.DataSerializers.VL_PDFReaderSerializerFactory.Initialize()
   at .cctor()
```
I am not even using Stride but it seems like it is depending on an outdated version of it?

**Comment by bj-rn** [comment]
I made some changes and export should work now (VL.PDFReader v. 1.1.1) in latest 6.7 previews, which use the latest Stride version (4.2.0.2232). I won’t work with 6.6 though.
If you need a version working with 6.6 you can fork the repo and downgrade to the appropriate version.
